---
database:
  host: localhost
  user: camunda
  name: workflow
  password: camunda
  port: 5431
  ssl_mode: disable
  batchSize: 2
kassette-server:
  url: http://localhost:8088
  batchSize: 3
kassette-agent:
  uid: camunda
tables:
  service_catalogue:
    track_column: id
    id_column: id
#  act_hi_actinst:
#    track_column: start_time_
#    id_column: id_
#  act_hi_detail:
#    track_column: time_
#    id_column: id_    
