version: '3'

services:
  kassette-agent:
    image: golang:1.20.4
    command: bash -c "cd /opt/kassette-ai/ && find . -name go.sum -o -name go.mod -delete && rm -f kassette-agent && go mod init kassette.ai/kassette-agent && go mod tidy && go build && chmod 0755 kassette-agent && ./kassette-agent"
    volumes:
      - .:/opt/kassette-ai/    

